public class Constants {
    
    public static final String ERROR_AGE = 'Wrong Age for this flight.';
    public static final String ERROR_DATE = 'This flight departed.';
    public static final String MAIL_SUBJECT = 'Batch was completed.';
    public static final String FLIGHT_STATUS_DECLINED = 'Declined';
    public static final Integer DELETE_FLIGH_DAYS = 29;
    public static final Integer NUMB_ZERO = 0;
    
}