public class Constants {
    
    public static final String ERROR_AGE = 'Wrong Age for this flight.';
    public static final String ERROR_DATE = 'This flight departed.';
    public static final String MAIL_SUBJECT = 'Batch was completed.';
    public static final String FLIGHT_STATUS_DECLINED = 'Declined';
    public static final String FLIGHT_STATUS_OFFER_PENDING = 'Offer Pending';
    public static final String FLIGHT_STATUS_REQUESTED = 'Requested';
    public static final String RESPONSE_BODY_NAME_EMPTY = 'The name must be not empty.';
    public static final String RESPONSE_BODY_AGE_NOT_INTEGER_TYPE = 'The age must be a number.';
    public static final String RESPONSE_BODY_DUPLICATE_TOURIST = 'This tourist is duplicate.';
    public static final String SPACE_CHARACTER = ' ';
    public static final String WEATHERBIT_IO_API_KEY = '15c19f9be3e140e7acd90f081ef2cfbc';
    public static final String WEATHERBIT_IO_END_POINT = 'https://api.weatherbit.io/v2.0/forecast/daily';
    public static final String NAMED_CREDENTIALS_WEATHERBIT = 'callout:WeatherAPI/';
    public static final String WEATHER_FORECAST_SERVICE_EXCEPTION_ERROR = 'An error occurred in the process.';
    public static final String HTTP_METHOD_GET = 'GET';
    public static final Integer DELETE_FLIGH_DAYS = 29;
    public static final Integer NUMB_ZERO = 0;
    public static final Integer RESPONSE_STATUS_CODE_200 = 200;
    public static final Integer RESPONSE_STATUS_CODE_404 = 404;
    public static final Integer RESPONSE_STATUS_CODE_409 = 409;       
}